//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userPermissionTestEntities : DbContext
    {
        public userPermissionTestEntities()
            : base("name=userPermissionTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<permissionInfo> permissionInfo { get; set; }
        public virtual DbSet<roleInfo> roleInfo { get; set; }
        public virtual DbSet<rolePermission> rolePermission { get; set; }
    }
}
