//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolePermission
    {
        public int roleID { get; set; }
        public int permissionID { get; set; }
        public string description { get; set; }
    
        public virtual permissionInfo permissionInfo { get; set; }
        public virtual roleInfo roleInfo { get; set; }
    }
}
